export const LANGUAGE_PHRASES = {
	CHAT : "Chat",
	CLOSE : "Close",
	ONLINE : "Online",
	NO_CONV_FOUND : "No conversations found!",
	NO_MESSAGES_FOUND : "No messages found!",
	DELETED_MEMBER : "Deleted Member",
	MESSAGE_DELETED : "This message was deleted",
	LAST_SEEN : "Last Seen ",
	MUTE_CONV : "Mute Conversation",
	CLEAR_CONV : "Clear Conversation",
	DELETE_CONV : "Delete Conversation",
	LEAVE_CONV : "Leave Conversation",
	JOIN_CONV : "Join Conversation",
	BLOCK_USER : "Block User",
	UNBLOCK_USER : "Unblock User",
	SEND_MESSAGE : "Send a message",
	DELETE : "Delete",
	IMAGE : "Image",
	AUDIO : "Audio",
	VIDEO : "Video",
	LOCATION : "Location",
	STICKER : "Sticker",
	GIF : "GIF",
	DOCUMENT : "Document",
	ATTACHMENT : "Attachment",
	SEND_ATTACHMENTS : "Send Attachments",
	MEMBERS : "Members",
	FILE_SIZE_WARNING : "File size should be less then 25mb",
	SEARCH : "Search",
	SEARCH_MEMBERS : "Search Members",
	SUGGESTED : "Suggested",
	MORE_USERS : "More Users",
	LOGIN : "Login",
	LOGOUT : "Logout",
	NAME : "Name",
	START : "Start",
	LOGIN_WITH_TEST_USERS : "OR Login with Test users",
	ENTER_NAME : "Please enter a name",
	USER_EXIST : "User already exist with this username",
	DELETE_FOR_ME : "Delete for me",
	DELETE_FOR_EVERYONE : "Delete for everyone",
	GROUP_CREATED : "Group created",
	GROUP_PHOTO_CHANGED : "Group photo updated",
	GROUP_TITLE_CHANGED : "Group title updated",
	GROUP_MEMBER_ADDED : "New member added in group",
	GROUP_MEMBER_REMOVED : "One member removed from group",
	GROUP_ADMIN_UPDATED : "Group admin updated",
	CONVERSATION_NOT_FOUND : "Conversation not fond",
	YOU : "You",
	REPLIES : "Replies",
	THREAD : "Thread",
	REPLY_IN_THREAD : "Reply in Thread",
	VIEW_THREAD : "View thread",
	START_OF_A_NEW_THREAD : "Start of a new thread",
	SEND_DIRECT_MESSAGE : "Also send as direct message",
	SEND_TO_CONVERSATION : "Also sent to the conversation",
	REPLY_OF_THREAD : "Reply of thread"
}

export const IMAGES = {
	LAUNCHER_ICON : "https://cdn.channelize.io/apps/web-widget/1.0.0/images/launcher-icon.svg",
	ANNA_SMITH : "https://cdn.channelize.io/apps/web-widget/1.0.0/images/anna-smith.jpg",
	KATRINA_CHARLEY : "https://cdn.channelize.io/apps/web-widget/1.0.0/images/katrina-charley.png",
	NATALIE_IVANOVIC : "https://cdn.channelize.io/apps/web-widget/1.0.0/images/natalie-ivanovic.jpeg",
	ERIC_ANDREWS : "https://cdn.channelize.io/apps/web-widget/1.0.0/images/eric-andrews.jpeg",
	GALLERY_ICON : "https:/cdn.channelize.io/apps/web-widget/1.0.0/images/gallery.png",
	AUDIO_ICON : "https://cdn.channelize.io/apps/web-widget/1.0.0/images/audio.png",
	VIDEO_ICON : "https://cdn.channelize.io/apps/web-widget/1.0.0/images/video.svg",
	LOCATION_ICON : "https://cdn.channelize.io/apps/web-widget/1.0.0/images/location.svg",
	STICKER_ICON : "https://cdn.channelize.io/apps/web-widget/1.0.0/images/sticker.png",
	GIF_ICON : "https://cdn.channelize.io/apps/web-widget/1.0.0/images/gif.png",
	AVTAR : "https://cdn.channelize.io/apps/web-widget/1.0.0/images/avtar.png",
	GROUP : "https://cdn.channelize.io/apps/web-widget/1.0.0/images/group.png",
	MESSAGE_LOADER : "https://cdn.channelize.io/apps/web-widget/1.0.0/images/image-loader.gif"
}

export const SETTINGS = {
	LOCATION_API_KEY : "AIzaSyBzrL8FaUvmYPIxEUd_VTPpqcACtPdniik",
	LOCATION_IMG_URL : "https://maps.googleapis.com/maps/api/staticmap",
	ALLOW_MESSAGE_THREADING: true,
	REACTION_SETTINGS : {
		enable: true,
		types: {
			"like": "👍",
			"dislike": "👎",
			"laughing": "😆",
			"angry": "😡"
		}
	}
}

export const ICONS = {
	"image" : "photo",
	"video" : "play_circle_outline",
	"file" : "attach_file",
	"audio" : "headset",
	"sticker" : "sentiment_very_satisfied",
	"gif" : "gif",
	"location" : "room",
	"document" : "insert_drive_file"
}